### ISSUE TITLE
Oddaja projekta

### ISSUE THREAD

**Issue by PezdirM14** [jaanos/APPR-2015-16-zagovori#23]
Pozdravljeni,
se opravičujem za pozno oddajo, vendar menim da sem projekt dokončal. Prosil bi, da pregledate, če vam projekt prevede in če vam ga, da mi ga dodate med zagovore.
Lep pozdrav

**Comment by jaanos** [comment]
Se opravičujem za pozen odgovor, sem bil odsoten.

Poročilo se prevede, tako da bom dodal projekt med oddaje. Če se še nisi, se lahko s profesorjem domeniš za termin zagovora.

Predlagal bi sicer, da se v grafih in zemljevidu znebiš eksponentne notacije (kjer je potrebno, podatke deli s 1000 ali 1000000 in v oznakah osi povej, za kakšne enote gre), ter da zadnji graf spremeniš v črtni graf z leti na osi x.

Če boš še kaj spreminjal, povej tukaj, da posodobim povezavo.

**Comment by PezdirM14** [comment]
Hvala za odgovor in svetovanje pri projektu. Vam bom sporocil, ce bom kaj spreminjal.

**Comment by PezdirM14** [comment]
Sedaj sem posodobil, prosil bi  vas če posodobite projekt tudi vi. Opazil sem še eno stvar. Pri drugem grafu v shiny-ju, ko izberem več držav kot eno se včasih zgodi da se izgubijo oznake(pike), čeprav jih imam na voljo v podatkih. Ko sem šel preveriti kaj vrne npr. "filter(zdruzena,Drzava==c("Austria","Belgium"))", mi ne vrne vseh podatkov, ki jih imam v tabeli "zdruzena". Mogoče veste zakaj? Lep pozdrav

**Comment by jaanos** [comment]
Da ti bo pravilno delovalo, uporabi
```R
filter(zdruzena, Drzava %in% c("Austria", "Belgium"))
```
Če namesto `%in%` uporabiš `==`, se namreč primerjata dva vektorja (stolpec `Drzava` in tvoj vektor), pri čemer pride do cikličnega dopolnjevanja ter tako dobiš lihe vrstice z vrednostjo `"Austria"` in sode vrstice z vrednostjo `"Belgium"`.

Bom posodobil povezavo - ko popraviš, mi javi, da jo spet posodobim.

**Comment by PezdirM14** [comment]
Sedaj sem popravil in vse deluje tako kot sem si zamislil, zato prosim da posodobite povezavo. Hvala in lep pozdrav.

**Comment by jaanos** [comment]
V redu, posodobljeno.
