### ISSUE TITLE
Oddaja projekta

### ISSUE THREAD

**Issue by StangeljL12** [jaanos/APPR-2015-16-zagovori#27]
Pozdravljeni,

pripravljena sem na oddajo projekta.

**Comment by jaanos** [comment]
Poročila pri meni ne prevede, ker v `uvoz.r` datoteka `PoMesecih.csv` ni navedena s pravilno velikostjo črk - ta mora biti ista kot pri samem imenu datoteke. Drugih pripomb nimam, tako da to popravi, pa bom dodal povezavo.

**Comment by StangeljL12** [comment]
Hvala, sem popravila, tako da zdaj lahko še enkrat preverite če poročilo prevede.

**Comment by jaanos** [comment]
V redu, zdaj se prevede, tako da bom dodal povezavo. Če se še nisi, se z @alenFMF domeni za termin zagovora.

Če bi še kaj spreminjala, mi javi, da posodobim povezavo.
