### ISSUE TITLE
Oddaja projekta

### ISSUE THREAD

**Issue by rahlocutnacigra** [jaanos/APPR-2015-16-zagovori#28]
Pozdravjeni, zaključila sem svoj projekt. Prosim vas, da dodate povezavo do mojega projekta. 
Lp, Manca Cör

**Comment by jaanos** [comment]
V redu, bom dodal. Če se še nisi, se s profesorjem domeni za termin zagovora.

Svetoval bi ti le, da zamenjaš naslov v Shiny aplikaciji. Če boš torej še kaj spreminjala, mi javi tukaj, da posodobim povezavo.

**Comment by rahlocutnacigra** [comment]
Hvala za opozorilo, sem spremenila ime. Najlepša hvala za vašo pomoč.

**Comment by jaanos** [comment]
V redu, bom posodobil.
