### ISSUE TITLE
Oddaja projekta

### ISSUE THREAD

**Issue by NadjaLegan** [jaanos/APPR-2015-16-zagovori#29]
Pozdravljeni,

pripravljena sem na oddajo projekta.

Lp, Nadja

**Comment by jaanos** [comment]
Pri meni poročila ne prevede - očitno gre za problem v knjižnici dplyr (hadley/dplyr#848), zaradi katerega `right_join` ne deluje, če imaš šumnike (ali druge posebne znake) v imenu stolpca, po katerem združuješ. Očitno so problem sicer že rešili v zadnji različici knjižnice. Vseeno bi te prosil, če se v `vizualizacija.r` izogneš temu problemu pri risanju zemljevida `ZEM_EU`:
```R
ZEM_EU <- ggplot() + geom_polygon(data = prihodkiEU %>% rename(name = Država) %>%
                          right_join(NOV, by = "name"),
                                   aes(x = long, y = lat, group = group, fill = `Prihodek v letu 2014`), 
                                   color = "white") +
  guides(fill = guide_colorbar(title = "Višina prihodkov")) +
  ggtitle("Prihodki od turizma v nekaterih evropskih državah")+
  xlim(-25, 45) + ylim(35, 75)
```

Svetoval bi ti še, da na zemljevidih Slovenije nekoliko zmanjšaš imena regij, da se ne bodo prekrivala, pri zemljevidu Evrope in zadnjem grafu pa podatke deliš z npr. 1000, da se številke ne bodo pojavljale v eksponentni notaciji (seveda označi, da gre za tisoče evrov oziroma nočitev).

Glede na to, da ne gre za tvojo napako, bom projekt smatral kot oddan, tako da se lahko s profesorjem domeniš za termin zagovora, če se še nisi. Povezavo bom sicer dodal, ko popraviš zgoraj omenjeno.

**Comment by NadjaLegan** [comment]
Hvala, sem vse popravila. Upam da bo sedaj prevedlo.

**Comment by jaanos** [comment]
Sedaj prevede, tako da bom dodal povezavo. Če bi še kaj spreminjala, mi javi tukaj, da jo posodobim.
