### ISSUE TITLE
projekt

### ISSUE THREAD

**Issue by MarvinHerzog** [jaanos/APPR-2015-16-zagovori#3]
Zaenkrat bi moralo delovati.
https://github.com/MarvinHerzog/APPR-2015-16

**Comment by jaanos** [comment]
Poročila pri meni ne prevede - v `libraries.r` kličeš `obdelava.r`, datoteka pa ima končnico `.R` (velika črka). To popravi, saj nekateri sistemi ločijo velikosti črk v datotekah.

**Comment by MarvinHerzog** [comment]
Ah, saj res. Sem popravil. Je sedaj v redu?

**Comment by jaanos** [comment]
Ja, sedaj je v redu. Bom dodal.
