### ISSUE TITLE
Deluje

### ISSUE THREAD

**Issue by PirnovarA** [jaanos/APPR-2015-16-zagovori#4]
Projekt naj bi sedaj deloval.

**Comment by jaanos** [comment]
Kot sem omenil v PirnovarA/APPR-2015-16#1, v `uvoz.r` kličeš programa s končnico `.r`, ustrezni datoteki pa imata končnico `.R` (velika črka). To popravi, saj nekateri sistemi ločijo velikosti črk v datotekah.

**Comment by PirnovarA** [comment]
Na mojem racunalniku sem preveril dvakrat in spremenil koncnici (za vsak slucaj) in imata obe datoteki koncnico .r . Bom preveril se enkrat, a naj bi bilo tako.

**Comment by jaanos** [comment]
Aha, git potem očitno tega ni zagrabil, ker operacijski sistem ni zaznal razlike. Mogoče bo najboljše, če imata datoteki kar končnico `.R`, pa to spremeniš tudi v programu.

**Comment by PirnovarA** [comment]
Evo, po dveh preimenovanjih datotek, je git ugotovil, da je tudi končnica druga. Tako da je zdej .r in naj bi vse delovalo.

**Comment by jaanos** [comment]
V redu, deluje. Bom dodal.
