### ISSUE TITLE
Druga faza

### ISSUE THREAD

**Issue by GalDrnovsek** [jaanos/APPR-2015-16-zagovori#7]
Prosim, če mi lahko pogledate projekt(mislim, da deluje).

**Comment by jaanos** [comment]
Uvoz pri meni ne deluje - poglej si komentar na commit GalDrnovsek/APPR-2015-16@ee9acaf69ab2c986ca423db4d39c37dd7ee73e57.

Če hočeš v Markdownu narediti seznam, za začetne zvezdice postavi še presledek.

Ko urediš, mi javi, da dodam povezavo.

**Comment by GalDrnovsek** [comment]
Sedaj uvoz v pdf pri meni deluje.

**Comment by jaanos** [comment]
V redu, sem dodal.
