### ISSUE TITLE
posodobitev verzije

### ISSUE THREAD

**Issue by vesnazupanc** [jaanos/APPR-2015-16-zagovori#8]
če je še možno bi posodobila verzijo: vesnazupanc/APPR-2015-16@75f7c2094776be3cdf26955d005230f94a32df94

**Comment by vesnazupanc** [comment]
še novejša verzija: vesnazupanc/APPR-2015-16@208a1e5d42e353a207269f7cb734a8be0f546ff6

**Comment by jaanos** [comment]
Sem posodobil.
